### ISSUE TITLE
Ability to use PUT requests for bot stats

### ISSUE THREAD

**Issue by circuitsacul** [botblock/api-worker#2]
AFAIK BotBlock will only allow POST requests for bot stats. dlist.gg uses PUT requests, resulting in a 405: Method not allowed.

<img width="553" alt="Screen Shot 2022-07-15 at 10 13 57 PM" src="https://user-images.githubusercontent.com/55721663/179334842-d1b8052f-8a3f-4b43-acd8-ea0221dc34b0.png">

**Comment by MattIPv4** [comment]
Moving this over to api-worker as the first step will be implementing support for this in the code before we can start tracking data for it.

**Comment by A5rocks** [comment]
I'm thinking an `api_post_method` optional field in the botlist JSON should be fine? ATM the stats endpoint is `api_post`, and we're providing an HTTP method for it.

On one hand, the field names won't make much sense. On the other hand, no new name needs to be made and other JSON files do not need to be updated.

**Comment by MattIPv4** [comment]
Agreed with that approach, seems like the best way to do it such that everything remains backwards compatible.

Just needs to be added in here: https://github.com/botblock/api-worker/blob/5c5469547e9f34d548fad0f2e70ebdb2759b6cc5/src/routes/count.js#L69
